# Generated by Django 4.2.13 on 2024-06-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='titulo')),
                ('subtitle', models.CharField(max_length=64, verbose_name='subtitulo')),
                ('content', models.CharField(max_length=1280, verbose_name='contenido')),
            ],
        ),
    ]
